// src/pages/Community.jsx
import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { motion } from 'framer-motion';
import { Users, Heart, Code, Palette, Lightbulb, Star, Calendar, MessageCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';
import CommunityJoinForm from '@/components/community/CommunityJoinForm';
import CommunityOnboarding from '@/components/community/CommunityOnboarding';

const Community = () => {
  const { toast } = useToast();
  const [showJoinForm, setShowJoinForm] = useState(false);

  const handleJoinClick = () => {
    setShowJoinForm(true);
    // Scroll to form
    setTimeout(() => {
      document.getElementById('community-join-form')?.scrollIntoView({ 
        behavior: 'smooth',
        block: 'start'
      });
    }, 100);
  };

  const offerings = [
    {
      icon: <Heart className="h-8 w-8" />,
      title: "Monthly Glow Circles",
      description: "Intimate gatherings where we share stories, celebrate achievements, and support each other's creative journeys.",
      frequency: "Every first Saturday",
      format: "Hybrid (Online + Offline)"
    },
    {
      icon: <Lightbulb className="h-8 w-8" />,
      title: "Tech & Story Labs",
      description: "Hands-on workshops where we explore the intersection of technology and storytelling through resin art.",
      frequency: "Bi-weekly",
      format: "Interactive Workshops"
    },
    {
      icon: <Code className="h-8 w-8" />,
      title: "Resin + Robotics Workshops",
      description: "Learn to integrate sensors, LEDs, and smart components into your resin creations.",
      frequency: "Monthly",
      format: "Technical Deep-dives"
    },
    {
      icon: <Users className="h-8 w-8" />,
      title: "Mentorship Pods",
      description: "Small group mentoring sessions with industry experts and successful community members.",
      frequency: "Weekly",
      format: "Small Groups (4-6 members)"
    }
  ];

  const communityValues = [
    {
      title: "Inclusive Innovation",
      description: "We believe the best ideas come from diverse perspectives and experiences."
    },
    {
      title: "Supportive Growth",
      description: "Every member's success is celebrated as a community achievement."
    },
    {
      title: "Creative Courage",
      description: "We encourage bold experiments and learn from every attempt."
    },
    {
      title: "Tech with Heart",
      description: "Technology should amplify human connection, not replace it."
    }
  ];

  const memberSpotlights = [
    {
      name: "Priya K.",
      title: "Software Engineer & Resin Artist",
      story: "Started as a weekend hobbyist, now runs her own createch studio in Bangalore.",
      achievement: "Featured in TechCrunch for her IoT-enabled resin installations"
    },
    {
      name: "Ananya M.",
      title: "Homemaker & Tech Enthusiast",
      story: "Discovered her passion for electronics through our workshops, now teaches kids coding through art.",
      achievement: "Launched 'Code & Craft' program in her local community"
    },
    {
      name: "Divya R.",
      title: "Product Designer",
      story: "Combined her design skills with resin art to create award-winning smart home accessories.",
      achievement: "Won 'Innovation in Design' at National Maker Fest"
    }
  ];

  return (
    <>
      <Helmet>
        <title>Nebulher Community - Women-Only Createch Ecosystem | Stasis Artis</title>
        <meta name="description" content="Join Nebulher, our women-only ecosystem for girl coders, creators, homemakers, and thinkers who refuse to pick just one title." />
      </Helmet>

      <div className="min-h-screen pt-20">
        {/* Hero Section */}
        <section className="py-20 pattern-bg">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center space-y-6 max-w-4xl mx-auto"
            >
              <h1 className="text-5xl md:text-6xl font-playfair font-bold">
                <span className="gradient-text">Nebulher</span> Community
              </h1>
              <p className="text-xl md:text-2xl text-gray-300">
                A Women-Only Ecosystem Powered by Stasis Artis
              </p>
              <div className="glass-effect rounded-2xl p-8 max-w-3xl mx-auto">
                <blockquote className="text-lg md:text-xl font-playfair italic">
                  "For girl coders, creators, homemakers, thinkers — who refuse to pick just one title."
                </blockquote>
                <p className="text-teal-400 mt-4">— The Nebulher Manifesto</p>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Community Offerings */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold gradient-text mb-4">
                Core Offerings
              </h2>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                Designed specifically for women who want to explore, create, and grow in the createch space
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {offerings.map((offering, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="glass-effect rounded-xl p-8 hover-lift group"
                >
                  <div className="space-y-6">
                    <div className="flex items-center space-x-4">
                      <div className="text-teal-400 group-hover:scale-110 transition-transform">
                        {offering.icon}
                      </div>
                      <h3 className="text-2xl font-playfair font-bold text-white">
                        {offering.title}
                      </h3>
                    </div>
                    
                    <p className="text-gray-300 leading-relaxed">
                      {offering.description}
                    </p>
                    
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
                      <div className="flex items-center space-x-2">
                        <Calendar className="h-4 w-4 text-teal-400" />
                        <span className="text-gray-300">{offering.frequency}</span>
                      </div>
                      <div className="flex items-center space-x-2">
                        <MessageCircle className="h-4 w-4 text-teal-400" />
                        <span className="text-gray-300">{offering.format}</span>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Community Values */}
        <section className="py-20 bg-gradient-to-b from-transparent to-gray-900/50">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
                Our <span className="gradient-text">Values</span>
              </h2>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                The principles that guide our community and shape every interaction
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {communityValues.map((value, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="glass-effect rounded-xl p-6 hover-lift text-center"
                >
                  <div className="space-y-4">
                    <div className="w-12 h-12 mx-auto rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center">
                      <Star className="h-6 w-6 text-black" />
                    </div>
                    <h3 className="text-xl font-semibold text-white">{value.title}</h3>
                    <p className="text-gray-300 leading-relaxed text-sm">{value.description}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Member Spotlights */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
                Member <span className="gradient-text">Spotlights</span>
              </h2>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                Celebrating the incredible women who are shaping the future of createch
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {memberSpotlights.map((member, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.2 }}
                  className="glass-effect rounded-xl p-6 hover-lift"
                >
                  <div className="space-y-4">
                    <div className="text-center">
                      <div className="w-16 h-16 mx-auto rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center text-black font-bold text-xl mb-4">
                        {member.name.charAt(0)}
                      </div>
                      <h3 className="text-xl font-semibold text-white">{member.name}</h3>
                      <p className="text-teal-400 text-sm">{member.title}</p>
                    </div>
                    
                    <p className="text-gray-300 text-sm leading-relaxed">
                      {member.story}
                    </p>
                    
                    <div className="bg-gradient-to-r from-teal-900/20 to-cyan-900/20 rounded-lg p-3">
                      <p className="text-xs text-gray-300">
                        <strong className="text-teal-400">Achievement:</strong> {member.achievement}
                      </p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Community Onboarding Info */}
        <section className="py-20 bg-gradient-to-b from-transparent to-gray-900/50">
          <div className="container mx-auto px-4">
            <CommunityOnboarding />
          </div>
        </section>

        {/* Community Impact */}
        <section className="py-20 bg-gradient-to-r from-teal-900/20 to-cyan-900/20">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <motion.div
                initial={{ opacity: 0, x: -50 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.8 }}
                className="space-y-6"
              >
                <h2 className="text-4xl font-playfair font-bold text-white">
                  Building the Future <span className="gradient-text">Together</span>
                </h2>
                <div className="space-y-4 text-gray-300 leading-relaxed">
                  <p>
                    Nebulher isn't just a community – it's a movement. We're proving that when women support women in tech and creativity, incredible things happen.
                  </p>
                  <p>
                    Our members have launched startups, won awards, changed careers, and most importantly, found their tribe of like-minded women who understand the unique challenges and opportunities we face.
                  </p>
                  <p>
                    Join us in redefining what it means to be a woman in the createch space. Your voice, your ideas, and your dreams matter here.
                  </p>
                </div>
                
                <div className="grid grid-cols-2 gap-6 pt-6">
                  <div className="text-center">
                    <div className="text-3xl font-bold gradient-text">200+</div>
                    <p className="text-gray-400 text-sm">Active Members</p>
                  </div>
                  <div className="text-center">
                    <div className="text-3xl font-bold gradient-text">50+</div>
                    <p className="text-gray-400 text-sm">Success Stories</p>
                  </div>
                  <div className="text-center">
                    <div className="text-3xl font-bold gradient-text">25+</div>
                    <p className="text-gray-400 text-sm">Monthly Events</p>
                  </div>
                  <div className="text-center">
                    <div className="text-3xl font-bold gradient-text">100%</div>
                    <p className="text-gray-400 text-sm">Women-Led</p>
                  </div>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: 50 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.8 }}
                className="glass-effect rounded-2xl p-8"
              >
                <img  
                  className="w-full h-64 object-cover rounded-xl mb-6" 
                  alt="Women working together on createch projects in the Nebulher community"
                 src="https://images.unsplash.com/photo-1653669486992-66a21d74d716" />
                <blockquote className="text-lg font-playfair italic text-center text-gray-300">
                  "Nebulher gave me the confidence to quit my corporate job and start my own createch studio. The support here is unmatched."
                </blockquote>
                <p className="text-teal-400 text-center mt-4">— Community Member</p>
              </motion.div>
            </div>
          </div>
        </section>

        {/* Join CTA */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center space-y-8 max-w-4xl mx-auto"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white">
                Ready to Join <span className="gradient-text">Nebulher</span>?
              </h2>
              <p className="text-xl text-gray-300">
                Whether you're a seasoned professional or just starting your journey, there's a place for you in our community.
              </p>
              <div className="glass-effect rounded-2xl p-8 max-w-2xl mx-auto">
                <h3 className="text-2xl font-semibold text-white mb-4">Membership Benefits</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-300">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400"></div>
                    <span>Access to all workshops</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400"></div>
                    <span>Mentorship opportunities</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400"></div>
                    <span>Exclusive community events</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400"></div>
                    <span>Project collaboration platform</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400"></div>
                    <span>Resource library access</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400"></div>
                    <span>Career support network</span>
                  </div>
                </div>
              </div>
              <Button
                size="lg"
                className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-8 py-3 rounded-full glow-effect hover-lift"
                onClick={handleJoinClick}
              >
                <Users className="mr-2 h-5 w-5" />
                Join Nebulher Community
              </Button>
              <p className="text-sm text-gray-400">
                Free to join • Women-only space • Supportive community
              </p>
            </motion.div>
          </div>
        </section>

        {/* Community Join Form */}
        {showJoinForm && (
          <section id="community-join-form" className="py-20 bg-gradient-to-b from-gray-900/50 to-black">
            <div className="container mx-auto px-4">
              <motion.div
                initial={{ opacity: 0, y: 50 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="text-center mb-12"
              >
                <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
                  Join <span className="gradient-text">Nebulher Community</span>
                </h2>
                <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                  Take the first step towards joining our vibrant community of women createch innovators
                </p>
              </motion.div>

              <CommunityJoinForm />
            </div>
          </section>
        )}
      </div>
    </>
  );
};

export default Community;

// src/app/pages/community/community.component.ts
import { Component, OnInit } from '@angular/core';
import { ToastService } from '@/shared/services/toast.service';

@Component({
  selector: 'app-community',
  templateUrl: './community.component.html',
  styleUrls: ['./community.component.scss']
})
export class CommunityComponent implements OnInit {
  showJoinForm = false;

  offerings = [
    {
      title: "Monthly Glow Circles",
      description: "Intimate gatherings where we share stories, celebrate achievements, and support each other's creative journeys.",
      frequency: "Every first Saturday",
      format: "Hybrid (Online + Offline)"
    },
    {
      title: "Tech & Story Labs",
      description: "Hands-on workshops where we explore the intersection of technology and storytelling through resin art.",
      frequency: "Bi-weekly",
      format: "Interactive Workshops"
    },
    {
      title: "Resin + Robotics Workshops",
      description: "Learn to integrate sensors, LEDs, and smart components into your resin creations.",
      frequency: "Monthly",
      format: "Technical Deep-dives"
    },
    {
      title: "Mentorship Pods",
      description: "Small group mentoring sessions with industry experts and successful community members.",
      frequency: "Weekly",
      format: "Small Groups (4-6 members)"
    }
  ];

  communityValues = [
    {
      title: "Inclusive Innovation",
      description: "We believe the best ideas come from diverse perspectives and experiences."
    },
    {
      title: "Supportive Growth",
      description: "Every member's success is celebrated as a community achievement."
    },
    {
      title: "Creative Courage",
      description: "We encourage bold experiments and learn from every attempt."
    },
    {
      title: "Tech with Heart",
      description: "Technology should amplify human connection, not replace it."
    }
  ];

  memberSpotlights = [
    {
      name: "Priya K.",
      title: "Software Engineer & Resin Artist",
      story: "Started as a weekend hobbyist, now runs her own createch studio in Bangalore.",
      achievement: "Featured in TechCrunch for her IoT-enabled resin installations"
    },
    {
      name: "Ananya M.",
      title: "Homemaker & Tech Enthusiast",
      story: "Discovered her passion for electronics through our workshops, now teaches kids coding through art.",
      achievement: "Launched 'Code & Craft' program in her local community"
    },
    {
      name: "Divya R.",
      title: "Product Designer",
      story: "Combined her design skills with resin art to create award-winning smart home accessories.",
      achievement: "Won 'Innovation in Design' at National Maker Fest"
    }
  ];

  constructor(private toastService: ToastService) { }

  ngOnInit(): void {
  }

  handleJoinClick(): void {
    this.showJoinForm = true;
    setTimeout(() => {
      document.getElementById('community-join-form')?.scrollIntoView({ 
        behavior: 'smooth',
        block: 'start'
      });
    }, 100);
  }
}
<div class="min-h-screen pt-20">
  <!-- Hero Section -->
  <section class="py-20 pattern-bg">
    <div class="container mx-auto px-4">
      <div class="text-center space-y-6 max-w-4xl mx-auto">
        <h1 class="text-5xl md:text-6xl font-playfair font-bold">
          <span class="gradient-text">Nebulher</span> Community
        </h1>
        <p class="text-xl md:text-2xl text-gray-300">
          A Women-Only Ecosystem Powered by Stasis Artis
        </p>
        <div class="glass-effect rounded-2xl p-8 max-w-3xl mx-auto">
          <blockquote class="text-lg md:text-xl font-playfair italic">
            "For girl coders, creators, homemakers, thinkers — who refuse to pick just one title."
          </blockquote>
          <p class="text-teal-400 mt-4">— The Nebulher Manifesto</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Community Offerings -->
  <section class="py-20">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <h2 class="text-4xl md:text-5xl font-playfair font-bold gradient-text mb-4">
          Core Offerings
        </h2>
        <p class="text-xl text-gray-300 max-w-3xl mx-auto">
          Designed specifically for women who want to explore, create, and grow in the createch space
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div 
          *ngFor="let offering of offerings; let i = index"
          class="glass-effect rounded-xl p-8 hover-lift group">
          <div class="space-y-6">
            <div class="flex items-center space-x-4">
              <div class="text-teal-400 group-hover:scale-110 transition-transform">
                <svg class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                </svg>
              </div>
              <h3 class="text-2xl font-playfair font-bold text-white">
                {{ offering.title }}
              </h3>
            </div>
            
            <p class="text-gray-300 leading-relaxed">
              {{ offering.description }}
            </p>
            
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
              <div class="flex items-center space-x-2">
                <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                <span class="text-gray-300">{{ offering.frequency }}</span>
              </div>
              <div class="flex items-center space-x-2">
                <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                </svg>
                <span class="text-gray-300">{{ offering.format }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Community Values -->
  <section class="py-20 bg-gradient-to-b from-transparent to-gray-900/50">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
          Our <span class="gradient-text">Values</span>
        </h2>
        <p class="text-xl text-gray-300 max-w-3xl mx-auto">
          The principles that guide our community and shape every interaction
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div 
          *ngFor="let value of communityValues; let i = index"
          class="glass-effect rounded-xl p-6 hover-lift text-center">
          <div class="space-y-4">
            <div class="w-12 h-12 mx-auto rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center">
              <svg class="h-6 w-6 text-black" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-white">{{ value.title }}</h3>
            <p class="text-gray-300 leading-relaxed text-sm">{{ value.description }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Member Spotlights -->
  <section class="py-20">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
          Member <span class="gradient-text">Spotlights</span>
        </h2>
        <p class="text-xl text-gray-300 max-w-3xl mx-auto">
          Celebrating the incredible women who are shaping the future of createch
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div 
          *ngFor="let member of memberSpotlights; let i = index"
          class="glass-effect rounded-xl p-6 hover-lift">
          <div class="space-y-4">
            <div class="text-center">
              <div class="w-16 h-16 mx-auto rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center text-black font-bold text-xl mb-4">
                {{ member.name.charAt(0) }}
              </div>
              <h3 class="text-xl font-semibold text-white">{{ member.name }}</h3>
              <p class="text-teal-400 text-sm">{{ member.title }}</p>
            </div>
            
            <p class="text-gray-300 text-sm leading-relaxed">
              {{ member.story }}
            </p>
            
            <div class="bg-gradient-to-r from-teal-900/20 to-cyan-900/20 rounded-lg p-3">
              <p class="text-xs text-gray-300">
                <strong class="text-teal-400">Achievement:</strong> {{ member.achievement }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Community Onboarding Info -->
  <section class="py-20 bg-gradient-to-b from-transparent to-gray-900/50">
    <div class="container mx-auto px-4">
      <app-community-onboarding></app-community-onboarding>
    </div>
  </section>

  <!-- Join CTA -->
  <section class="py-20">
    <div class="container mx-auto px-4">
      <div class="text-center space-y-8 max-w-4xl mx-auto">
        <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white">
          Ready to Join <span class="gradient-text">Nebulher</span>?
        </h2>
        <p class="text-xl text-gray-300">
          Whether you're a seasoned professional or just starting your journey, there's a place for you in our community.
        </p>
        <div class="glass-effect rounded-2xl p-8 max-w-2xl mx-auto">
          <h3 class="text-2xl font-semibold text-white mb-4">Membership Benefits</h3>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-300">
            <div 
              *ngFor="let benefit of [
                'Access to all workshops',
                'Mentorship opportunities',
                'Exclusive community events',
                'Project collaboration platform',
                'Resource library access',
                'Career support network'
              ]"
              class="flex items-center space-x-2">
              <div class="w-2 h-2 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400"></div>
              <span>{{ benefit }}</span>
            </div>
          </div>
        </div>
        <app-button
          size="lg"
          className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-8 py-3 rounded-full glow-effect hover-lift"
          (onClick)="handleJoinClick()">
          <svg class="mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m13.5-9a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z" />
          </svg>
          Join Nebulher Community
        </app-button>
        <p class="text-sm text-gray-400">
          Free to join • Women-only space • Supportive community
        </p>
      </div>
    </div>
  </section>

  <!-- Community Join Form -->
  <section 
    *ngIf="showJoinForm" 
    id="community-join-form" 
    class="py-20 bg-gradient-to-b from-gray-900/50 to-black">
    <div class="container mx-auto px-4">
      <div class="text-center mb-12">
        <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
          Join <span class="gradient-text">Nebulher Community</span>
        </h2>
        <p class="text-xl text-gray-300 max-w-3xl mx-auto">
          Take the first step towards joining our vibrant community of women createch innovators
        </p>
      </div>

      <app-community-join-form></app-community-join-form>
    </div>
  </section>
</div>
