// src/app/pages/bulk-orders/bulk-orders.component.ts
import { Component, OnInit } from '@angular/core';
import { ToastService } from '@/shared/services/toast.service';

@Component({
  selector: 'app-bulk-orders',
  templateUrl: './bulk-orders.component.html',
  styleUrls: ['./bulk-orders.component.scss']
})
export class BulkOrdersComponent implements OnInit {

  educationOfferings = [
    {
      title: "Creative Learning Kits",
      description: "Resin-based educational kits designed to make learning interactive and memorable",
      features: ["Age-appropriate materials", "Curriculum integration guides", "Safety protocols", "Teacher training included"],
      suitableFor: "Schools, Colleges, Educational Institutions"
    },
    {
      title: "Fusion Workshops",
      description: "Hands-on workshops combining resin art with technology for STEAM education",
      features: ["Expert facilitators", "All materials provided", "Project-based learning", "Student certificates"],
      suitableFor: "Schools, Summer Camps, Educational Programs"
    },
    {
      title: "Art-Tech Curriculum Modules",
      description: "Complete curriculum modules integrating createch into existing programs",
      features: ["Lesson plans", "Assessment rubrics", "Digital resources", "Ongoing support"],
      suitableFor: "Educational Boards, Universities, Training Centers"
    },
    {
      title: "ATL/STEM Integration",
      description: "Specialized programs for Atal Tinkering Labs and STEM initiatives",
      features: ["ATL-compliant activities", "Innovation projects", "Mentor support", "Competition preparation"],
      suitableFor: "ATL Labs, STEM Centers, Innovation Hubs"
    }
  ];

  corporateOfferings = [
    {
      title: "Team Bonding Resin Sessions",
      description: "Interactive team-building activities that create lasting memories and stronger bonds",
      features: ["Professional facilitation", "Custom themes", "Take-home creations", "Team challenges"],
      benefits: ["Improved collaboration", "Stress relief", "Creative thinking", "Memorable experience"]
    },
    {
      title: "Smart Corporate Gifting",
      description: "Custom tech-enhanced resin items perfect for corporate gifts and awards",
      features: ["Brand integration", "NFC/QR embedding", "Custom packaging", "Bulk pricing"],
      benefits: ["Unique brand presence", "Tech-forward image", "Memorable impact", "Sustainable materials"]
    },
    {
      title: "Custom Branding Solutions",
      description: "Resin installations and products featuring your brand in innovative ways",
      features: ["Logo embedding", "Color matching", "Interactive elements", "Installation support"],
      benefits: ["Brand differentiation", "Modern aesthetics", "Interactive engagement", "Long-lasting impact"]
    }
  ];

  pricingTiers = [
    {
      quantity: "25-50 Units",
      discount: "10% Off",
      features: ["Standard packaging", "Basic customization", "Email support", "2-week delivery"],
      bestFor: "Small teams, Pilot programs"
    },
    {
      quantity: "51-100 Units",
      discount: "15% Off",
      features: ["Premium packaging", "Advanced customization", "Priority support", "1-week delivery"],
      bestFor: "Medium organizations, Events"
    },
    {
      quantity: "100+ Units",
      discount: "20% Off",
      features: ["Luxury packaging", "Full customization", "Dedicated account manager", "Express delivery"],
      bestFor: "Large corporations, Institutions"
    }
  ];

  constructor(private toastService: ToastService) { }

  ngOnInit(): void {
  }

  handleRequestBulkQuote(): void {
    const phoneNumber = "919025486901";
    const message = encodeURIComponent("Hi! I'm interested in bulk orders for my organization. Could you please provide a detailed quote and discuss our requirements? We're looking at educational/corporate solutions from Stasis Artis.");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    window.open(whatsappUrl, '_blank');
  }

  handleScheduleConsultation(): void {
    const phoneNumber = "919025486901";
    const message = encodeURIComponent("Hi! I'd like to schedule a consultation for bulk orders. We're interested in createch solutions for our organization and would like to discuss our specific needs, timeline, and pricing options.");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    window.open(whatsappUrl, '_blank');
  }
}
<div class="min-h-screen pt-20">
  <!-- Hero Section -->
  <section class="py-20 pattern-bg">
    <div class="container mx-auto px-4">
      <div class="text-center space-y-6 max-w-4xl mx-auto">
        <h1 class="text-5xl md:text-6xl font-playfair font-bold">
          <span class="gradient-text">Bulk Orders</span>
        </h1>
        <p class="text-xl md:text-2xl text-gray-300">
          Schools, Colleges & Corporates
        </p>
        <div class="glass-effect rounded-2xl p-6 max-w-2xl mx-auto">
          <p class="text-lg text-gray-300">
            Transforming education and corporate experiences through createch innovation at scale
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Education Section -->
  <section class="py-20">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <div class="flex items-center justify-center space-x-4 mb-4">
          <svg class="h-12 w-12 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l9-5-9-5-9 5 9 5z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
          </svg>
          <h2 class="text-4xl md:text-5xl font-playfair font-bold gradient-text">
            Education Solutions
          </h2>
        </div>
        <p class="text-xl text-gray-300 max-w-3xl mx-auto">
          Bringing createch innovation to classrooms, labs, and learning spaces across India
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div 
          *ngFor="let offering of educationOfferings; let i = index"
          class="glass-effect rounded-xl p-8 hover-lift">
          <div class="space-y-6">
            <h3 class="text-2xl font-playfair font-bold text-white">
              {{ offering.title }}
            </h3>
            
            <p class="text-gray-300 leading-relaxed">
              {{ offering.description }}
            </p>
            
            <div class="space-y-3">
              <h4 class="text-lg font-semibold text-teal-400">Features:</h4>
              <div 
                *ngFor="let feature of offering.features"
                class="flex items-center space-x-3">
                <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
                <span class="text-gray-300 text-sm">{{ feature }}</span>
              </div>
            </div>
            
            <div class="bg-gradient-to-r from-teal-900/20 to-cyan-900/20 rounded-lg p-4">
              <p class="text-sm text-gray-300">
                <strong class="text-teal-400">Suitable for:</strong> {{ offering.suitableFor }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Corporate Section -->
  <section class="py-20 bg-gradient-to-b from-transparent to-gray-900/50">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <div class="flex items-center justify-center space-x-4 mb-4">
          <svg class="h-12 w-12 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
          </svg>
          <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white">
            Corporate <span class="gradient-text">Solutions</span>
          </h2>
        </div>
        <p class="text-xl text-gray-300 max-w-3xl mx-auto">
          Elevate your corporate culture and brand presence with innovative createch experiences
        </p>
      </div>

      <div class="space-y-12">
        <div 
          *ngFor="let offering of corporateOfferings; let i = index"
          class="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center"
          [class.lg:grid-flow-col-dense]="i % 2 === 1">
          
          <div class="space-y-6" [class.lg:col-start-2]="i % 2 === 1">
            <h3 class="text-3xl font-playfair font-bold text-white">
              {{ offering.title }}
            </h3>
            
            <p class="text-xl text-gray-300 leading-relaxed">
              {{ offering.description }}
            </p>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div class="space-y-3">
                <h4 class="text-lg font-semibold text-teal-400">Features:</h4>
                <div 
                  *ngFor="let feature of offering.features"
                  class="flex items-center space-x-3">
                  <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                  </svg>
                  <span class="text-gray-300 text-sm">{{ feature }}</span>
                </div>
              </div>
              
              <div class="space-y-3">
                <h4 class="text-lg font-semibold text-teal-400">Benefits:</h4>
                <div 
                  *ngFor="let benefit of offering.benefits"
                  class="flex items-center space-x-3">
                  <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                  </svg>
                  <span class="text-gray-300 text-sm">{{ benefit }}</span>
                </div>
              </div>
            </div>
            
            <app-button
              className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-6 py-3 rounded-full hover-lift"
              (onClick)="handleRequestBulkQuote()">
              Coming Soon
            </app-button>
          </div>
          
          <div [class.lg:col-start-1]="i % 2 === 1">
            <div class="glass-effect rounded-2xl p-4 hover-lift">
              <img  
                class="w-full h-80 object-cover rounded-xl" 
                [alt]="offering.title + ' in action'"
                src="https://images.unsplash.com/photo-1552664730-d307ca884978" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Pricing Tiers -->
  <section class="py-20">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
          Pricing <span class="gradient-text">Tiers</span>
        </h2>
        <p class="text-xl text-gray-300 max-w-3xl mx-auto">
          Flexible pricing options designed to meet your organization's needs and budget
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div 
          *ngFor="let tier of pricingTiers; let i = index"
          class="glass-effect rounded-xl p-8 hover-lift text-center"
          [class.ring-2]="i === 1"
          [class.ring-teal-400]="i === 1"
          [class.scale-105]="i === 1">
          <div class="space-y-6">
            <div>
              <h3 class="text-2xl font-semibold text-white mb-2">{{ tier.quantity }}</h3>
              <div class="text-3xl font-bold gradient-text">{{ tier.discount }}</div>
              <p class="text-gray-400 text-sm mt-2">{{ tier.bestFor }}</p>
            </div>
            
            <div class="space-y-3">
              <div 
                *ngFor="let feature of tier.features"
                class="flex items-center space-x-3">
                <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
                <span class="text-gray-300 text-sm">{{ feature }}</span>
              </div>
            </div>
            
            <app-button
              [variant]="i === 1 ? 'default' : 'outline'"
              [className]="'w-full font-semibold py-3 rounded-full hover-lift ' + (i === 1 ? 'bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black' : 'border-teal-400 text-teal-400 hover:bg-teal-400 hover:text-black')"
              (onClick)="handleRequestBulkQuote()">
              {{ i === 1 ? "Coming Soon" : "Coming Soon" }}
            </app-button>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- CTA Section -->
  <section class="py-20 bg-gradient-to-r from-teal-900/20 to-cyan-900/20">
    <div class="container mx-auto px-4">
      <div class="text-center space-y-8 max-w-4xl mx-auto">
        <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white">
          Ready to Transform Your <span class="gradient-text">Organization</span>?
        </h2>
        <p class="text-xl text-gray-300">
          Whether you're an educational institution looking to innovate learning or a corporation seeking unique experiences, we're here to help.
        </p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <app-button
            size="lg"
            className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-8 py-3 rounded-full glow-effect hover-lift"
            (onClick)="handleRequestBulkQuote()">
            <svg class="mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
            </svg>
            Request Bulk Quote
          </app-button>
          <app-button
            variant="outline"
            size="lg"
            className="border-teal-400 text-teal-400 hover:bg-teal-400 hover:text-black px-8 py-3 rounded-full hover-lift"
            (onClick)="handleScheduleConsultation()">
            <svg class="mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
            Schedule Consultation
          </app-button>
        </div>
        <div class="text-sm text-gray-400 space-y-1">
          <p>💬 WhatsApp: +91 90254 86901</p>
          <p>Free consultation • Custom solutions • Nationwide delivery</p>
        </div>
      </div>
    </div>
  </section>
</div>

// src/pages/BulkOrders.jsx
import React from 'react';
import { Helmet } from 'react-helmet';
import { motion } from 'framer-motion';
import { GraduationCap, Building, Package, Users, Truck, Calendar, CheckCircle, Star } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';

const BulkOrders = () => {
  const { toast } = useToast();

  const handleRequestBulkQuote = () => {
    const phoneNumber = "919025486901"; // +91 90254 86901 in international format
    const message = encodeURIComponent("Hi! I'm interested in bulk orders for my organization. Could you please provide a detailed quote and discuss our requirements? We're looking at educational/corporate solutions from Stasis Artis.");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    // Open WhatsApp in a new tab
    window.open(whatsappUrl, '_blank');
  };

  const handleScheduleConsultation = () => {
    const phoneNumber = "919025486901"; // +91 90254 86901 in international format
    const message = encodeURIComponent("Hi! I'd like to schedule a consultation for bulk orders. We're interested in createch solutions for our organization and would like to discuss our specific needs, timeline, and pricing options.");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    // Open WhatsApp in a new tab
    window.open(whatsappUrl, '_blank');
  };

  const educationOfferings = [
    {
      title: "Creative Learning Kits",
      description: "Resin-based educational kits designed to make learning interactive and memorable",
      features: ["Age-appropriate materials", "Curriculum integration guides", "Safety protocols", "Teacher training included"],
      suitableFor: "Schools, Colleges, Educational Institutions"
    },
    {
      title: "Fusion Workshops",
      description: "Hands-on workshops combining resin art with technology for STEAM education",
      features: ["Expert facilitators", "All materials provided", "Project-based learning", "Student certificates"],
      suitableFor: "Schools, Summer Camps, Educational Programs"
    },
    {
      title: "Art-Tech Curriculum Modules",
      description: "Complete curriculum modules integrating createch into existing programs",
      features: ["Lesson plans", "Assessment rubrics", "Digital resources", "Ongoing support"],
      suitableFor: "Educational Boards, Universities, Training Centers"
    },
    {
      title: "ATL/STEM Integration",
      description: "Specialized programs for Atal Tinkering Labs and STEM initiatives",
      features: ["ATL-compliant activities", "Innovation projects", "Mentor support", "Competition preparation"],
      suitableFor: "ATL Labs, STEM Centers, Innovation Hubs"
    }
  ];

  const corporateOfferings = [
    {
      title: "Team Bonding Resin Sessions",
      description: "Interactive team-building activities that create lasting memories and stronger bonds",
      features: ["Professional facilitation", "Custom themes", "Take-home creations", "Team challenges"],
      benefits: ["Improved collaboration", "Stress relief", "Creative thinking", "Memorable experience"]
    },
    {
      title: "Smart Corporate Gifting",
      description: "Custom tech-enhanced resin items perfect for corporate gifts and awards",
      features: ["Brand integration", "NFC/QR embedding", "Custom packaging", "Bulk pricing"],
      benefits: ["Unique brand presence", "Tech-forward image", "Memorable impact", "Sustainable materials"]
    },
    {
      title: "Custom Branding Solutions",
      description: "Resin installations and products featuring your brand in innovative ways",
      features: ["Logo embedding", "Color matching", "Interactive elements", "Installation support"],
      benefits: ["Brand differentiation", "Modern aesthetics", "Interactive engagement", "Long-lasting impact"]
    }
  ];

  const pricingTiers = [
    {
      quantity: "25-50 Units",
      discount: "10% Off",
      features: ["Standard packaging", "Basic customization", "Email support", "2-week delivery"],
      bestFor: "Small teams, Pilot programs"
    },
    {
      quantity: "51-100 Units",
      discount: "15% Off",
      features: ["Premium packaging", "Advanced customization", "Priority support", "1-week delivery"],
      bestFor: "Medium organizations, Events"
    },
    {
      quantity: "100+ Units",
      discount: "20% Off",
      features: ["Luxury packaging", "Full customization", "Dedicated account manager", "Express delivery"],
      bestFor: "Large corporations, Institutions"
    }
  ];

  return (
    <>
      <Helmet>
        <title>Bulk Orders - Schools, Colleges & Corporates | Stasis Artis</title>
        <meta name="description" content="Bulk orders for educational institutions and corporates. Creative learning kits, fusion workshops, team bonding sessions, and smart corporate gifting." />
      </Helmet>

      <div className="min-h-screen pt-20">
        {/* Hero Section */}
        <section className="py-20 pattern-bg">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center space-y-6 max-w-4xl mx-auto"
            >
              <h1 className="text-5xl md:text-6xl font-playfair font-bold">
                <span className="gradient-text">Bulk Orders</span>
              </h1>
              <p className="text-xl md:text-2xl text-gray-300">
                Schools, Colleges & Corporates
              </p>
              <div className="glass-effect rounded-2xl p-6 max-w-2xl mx-auto">
                <p className="text-lg text-gray-300">
                  Transforming education and corporate experiences through createch innovation at scale
                </p>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Education Section */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <div className="flex items-center justify-center space-x-4 mb-4">
                <GraduationCap className="h-12 w-12 text-teal-400" />
                <h2 className="text-4xl md:text-5xl font-playfair font-bold gradient-text">
                  Education Solutions
                </h2>
              </div>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                Bringing createch innovation to classrooms, labs, and learning spaces across India
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {educationOfferings.map((offering, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="glass-effect rounded-xl p-8 hover-lift"
                >
                  <div className="space-y-6">
                    <h3 className="text-2xl font-playfair font-bold text-white">
                      {offering.title}
                    </h3>
                    
                    <p className="text-gray-300 leading-relaxed">
                      {offering.description}
                    </p>
                    
                    <div className="space-y-3">
                      <h4 className="text-lg font-semibold text-teal-400">Features:</h4>
                      {offering.features.map((feature, featureIndex) => (
                        <div key={featureIndex} className="flex items-center space-x-3">
                          <CheckCircle className="h-4 w-4 text-teal-400" />
                          <span className="text-gray-300 text-sm">{feature}</span>
                        </div>
                      ))}
                    </div>
                    
                    <div className="bg-gradient-to-r from-teal-900/20 to-cyan-900/20 rounded-lg p-4">
                      <p className="text-sm text-gray-300">
                        <strong className="text-teal-400">Suitable for:</strong> {offering.suitableFor}
                      </p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Corporate Section */}
        <section className="py-20 bg-gradient-to-b from-transparent to-gray-900/50">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <div className="flex items-center justify-center space-x-4 mb-4">
                <Building className="h-12 w-12 text-teal-400" />
                <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white">
                  Corporate <span className="gradient-text">Solutions</span>
                </h2>
              </div>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                Elevate your corporate culture and brand presence with innovative createch experiences
              </p>
            </motion.div>

            <div className="space-y-12">
              {corporateOfferings.map((offering, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.2 }}
                  className={`grid grid-cols-1 lg:grid-cols-2 gap-8 items-center ${
                    index % 2 === 1 ? 'lg:grid-flow-col-dense' : ''
                  }`}
                >
                  <div className={`space-y-6 ${index % 2 === 1 ? 'lg:col-start-2' : ''}`}>
                    <h3 className="text-3xl font-playfair font-bold text-white">
                      {offering.title}
                    </h3>
                    
                    <p className="text-xl text-gray-300 leading-relaxed">
                      {offering.description}
                    </p>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="space-y-3">
                        <h4 className="text-lg font-semibold text-teal-400">Features:</h4>
                        {offering.features.map((feature, featureIndex) => (
                          <div key={featureIndex} className="flex items-center space-x-3">
                            <Star className="h-4 w-4 text-teal-400" />
                            <span className="text-gray-300 text-sm">{feature}</span>
                          </div>
                        ))}
                      </div>
                      
                      <div className="space-y-3">
                        <h4 className="text-lg font-semibold text-teal-400">Benefits:</h4>
                        {offering.benefits.map((benefit, benefitIndex) => (
                          <div key={benefitIndex} className="flex items-center space-x-3">
                            <CheckCircle className="h-4 w-4 text-teal-400" />
                            <span className="text-gray-300 text-sm">{benefit}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                    
                    <Button
                      className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-6 py-3 rounded-full hover-lift"
                      onClick={handleRequestBulkQuote}
                    >
                      Comming Soon
                    </Button>
                  </div>
                  
                  <div className={`${index % 2 === 1 ? 'lg:col-start-1' : ''}`}>
                    <div className="glass-effect rounded-2xl p-4 hover-lift">
                      <img  
                        className="w-full h-80 object-cover rounded-xl" 
                        alt={`${offering.title} in action`}
                       src="https://images.unsplash.com/photo-1552664730-d307ca884978" />
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing Tiers */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
                Pricing <span className="gradient-text">Tiers</span>
              </h2>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                Flexible pricing options designed to meet your organization's needs and budget
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {pricingTiers.map((tier, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.2 }}
                  className={`glass-effect rounded-xl p-8 hover-lift text-center ${
                    index === 1 ? 'ring-2 ring-teal-400 scale-105' : ''
                  }`}
                >
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-2xl font-semibold text-white mb-2">{tier.quantity}</h3>
                      <div className="text-3xl font-bold gradient-text">{tier.discount}</div>
                      <p className="text-gray-400 text-sm mt-2">{tier.bestFor}</p>
                    </div>
                    
                    <div className="space-y-3">
                      {tier.features.map((feature, featureIndex) => (
                        <div key={featureIndex} className="flex items-center space-x-3">
                          <CheckCircle className="h-4 w-4 text-teal-400" />
                          <span className="text-gray-300 text-sm">{feature}</span>
                        </div>
                      ))}
                    </div>
                    
                    <Button
                      variant={index === 1 ? "default" : "outline"}
                      className={`w-full ${
                        index === 1 
                          ? "bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black" 
                          : "border-teal-400 text-teal-400 hover:bg-teal-400 hover:text-black"
                      } font-semibold py-3 rounded-full hover-lift`}
                      onClick={handleRequestBulkQuote}
                    >
                      {/* {index === 1 ? "Most Popular" : "Get Started"} */}
                      {index === 1 ? "Comming Soon" : "Comming Soon"}
                    </Button>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Process & Logistics */}
        <section className="py-20 bg-gradient-to-b from-transparent to-gray-900/50">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
                Process & <span className="gradient-text">Logistics</span>
              </h2>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                Streamlined ordering process with reliable delivery and comprehensive support
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {[
                {
                  icon: <Users className="h-8 w-8" />,
                  title: "Consultation",
                  description: "Free consultation to understand your specific needs and customize solutions"
                },
                {
                  icon: <Package className="h-8 w-8" />,
                  title: "Custom Packaging",
                  description: "Professional packaging with your branding and detailed instruction materials"
                },
                {
                  icon: <Truck className="h-8 w-8" />,
                  title: "Delivery Logistics",
                  description: "Reliable delivery across India with tracking and insurance coverage"
                },
                {
                  icon: <Calendar className="h-8 w-8" />,
                  title: "Workshop Facilitation",
                  description: "Expert facilitators available for on-site workshops and training sessions"
                }
              ].map((process, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="glass-effect rounded-xl p-6 hover-lift text-center"
                >
                  <div className="text-teal-400 mb-4 flex justify-center">
                    {process.icon}
                  </div>
                  <h3 className="text-xl font-semibold text-white mb-3">{process.title}</h3>
                  <p className="text-gray-300 leading-relaxed text-sm">{process.description}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Success Stories */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white mb-4">
                Success <span className="gradient-text">Stories</span>
              </h2>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <motion.div
                initial={{ opacity: 0, x: -50 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.8 }}
                className="glass-effect rounded-xl p-8"
              >
                <div className="space-y-4">
                  <div className="flex items-center space-x-4">
                    <GraduationCap className="h-8 w-8 text-teal-400" />
                    <div>
                      <h3 className="text-xl font-semibold text-white">Delhi Public School</h3>
                      <p className="text-gray-400 text-sm">500 Student Workshop Series</p>
                    </div>
                  </div>
                  <blockquote className="text-gray-300 italic">
                    "The createch workshops transformed how our students think about the intersection of art and technology. The engagement levels were unprecedented."
                  </blockquote>
                  <p className="text-teal-400 text-sm">— Principal, DPS Bangalore</p>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: 50 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.8 }}
                className="glass-effect rounded-xl p-8"
              >
                <div className="space-y-4">
                  <div className="flex items-center space-x-4">
                    <Building className="h-8 w-8 text-teal-400" />
                    <div>
                      <h3 className="text-xl font-semibold text-white">Tech Mahindra</h3>
                      <p className="text-gray-400 text-sm">Corporate Team Building</p>
                    </div>
                  </div>
                  <blockquote className="text-gray-300 italic">
                    "The smart resin team-building session was unlike anything we've done before. It brought our teams closer while showcasing innovation."
                  </blockquote>
                  <p className="text-teal-400 text-sm">— HR Director, Tech Mahindra</p>
                </div>
              </motion.div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 bg-gradient-to-r from-teal-900/20 to-cyan-900/20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-center space-y-8 max-w-4xl mx-auto"
            >
              <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white">
                Ready to Transform Your <span className="gradient-text">Organization</span>?
              </h2>
              <p className="text-xl text-gray-300">
                Whether you're an educational institution looking to innovate learning or a corporation seeking unique experiences, we're here to help.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button
                  size="lg"
                  className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-8 py-3 rounded-full glow-effect hover-lift"
                  onClick={handleRequestBulkQuote}
                >
                  <Package className="mr-2 h-5 w-5" />
                  Request Bulk Quote
                </Button>
                <Button
                  variant="outline"
                  size="lg"
                  className="border-teal-400 text-teal-400 hover:bg-teal-400 hover:text-black px-8 py-3 rounded-full hover-lift"
                  onClick={handleScheduleConsultation}
                >
                  <Calendar className="mr-2 h-5 w-5" />
                  Schedule Consultation
                </Button>
              </div>
              <div className="text-sm text-gray-400 space-y-1">
                <p>💬 WhatsApp: +91 90254 86901</p>
                <p>Free consultation • Custom solutions • Nationwide delivery</p>
              </div>
            </motion.div>
          </div>
        </section>
      </div>
    </>
  );
};

export default BulkOrders;
