// src/components/contact/ContactCTA.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { MessageCircle, Phone } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';

const ContactCTA = () => {
  const { toast } = useToast();

  const handleWhatsAppClick = () => {
    const phoneNumber = "919025486901"; // +91 90254 86901 in international format
    const message = encodeURIComponent("Hi! I'm interested in learning more about Stasis Artis and your createch solutions. Could we discuss how you can help with my project?");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    // Open WhatsApp in a new tab
    window.open(whatsappUrl, '_blank');
  };

  const handleScheduleCall = () => {
    const phoneNumber = "919025486901"; // +91 90254 86901 in international format
    const message = encodeURIComponent("Hi! I'd like to schedule a call to discuss my createch project requirements. When would be a good time for a consultation?");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    // Open WhatsApp in a new tab
    window.open(whatsappUrl, '_blank');
  };

  return (
    <section className="py-20 bg-gradient-to-r from-teal-900/20 to-cyan-900/20">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center space-y-8 max-w-4xl mx-auto"
        >
          <h2 className="text-4xl md:text-5xl font-playfair font-bold text-white">
            Ready to Start Your <span className="gradient-text">Journey</span>?
          </h2>
          <p className="text-xl text-gray-300">
            Whether you have a specific project in mind or just want to explore possibilities, we're here to help you discover what's possible when art meets technology.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button
              size="lg"
              className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-8 py-3 rounded-full glow-effect hover-lift"
              onClick={handleWhatsAppClick}
            >
              <MessageCircle className="mr-2 h-5 w-5" />
              Start a Conversation
            </Button>
            <Button
              variant="outline"
              size="lg"
              className="border-teal-400 text-teal-400 hover:bg-teal-400 hover:text-black px-8 py-3 rounded-full hover-lift"
              onClick={handleScheduleCall}
            >
              <Phone className="mr-2 h-5 w-5" />
              Schedule a Call
            </Button>
          </div>
          <div className="text-sm text-gray-400 space-y-1">
            <p>💬 WhatsApp: +91 90254 86901</p>
            <p>Quick response • Personalized consultation • Free initial discussion</p>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default ContactCTA;

// src/app/components/contact/contact-cta/contact-cta.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-contact-cta',
  templateUrl: './contact-cta.component.html',
  styleUrls: ['./contact-cta.component.scss']
})
export class ContactCtaComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  handleWhatsAppClick(): void {
    const phoneNumber = "919025486901";
    const message = encodeURIComponent("Hi! I'm interested in learning more about Stasis Artis and your createch solutions. Could we discuss how you can help with my project?");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    window.open(whatsappUrl, '_blank');
  }

  handleScheduleCall(): void {
    const phoneNumber = "919025486901";
    const message = encodeURIComponent("Hi! I'd like to schedule a call to discuss my createch project requirements. When would be a good time for a consultation?");
    const whatsappUrl = `https://wa.me/${phoneNumber}?text=${message}`;
    
    window.open(whatsappUrl, '_blank');
  }
}
<section class="py-20 bg-gradient-to-r from-teal-900/20 to-cyan-900/20">
  <div class="container mx-auto px-4">
    <div class="text-center space-y-8 max-w-4xl mx-auto">
      <h2 class="text-4xl md:text-5xl font-playfair font-bold text-white">
        Ready to Start Your <span class="gradient-text">Journey</span>?
      </h2>
      <p class="text-xl text-gray-300">
        Whether you have a specific project in mind or just want to explore possibilities, we're here to help you discover what's possible when art meets technology.
      </p>
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <app-button
          size="lg"
          className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-black font-semibold px-8 py-3 rounded-full glow-effect hover-lift"
          (onClick)="handleWhatsAppClick()">
          <svg class="mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
          </svg>
          Start a Conversation
        </app-button>
        <app-button
          variant="outline"
          size="lg"
          className="border-teal-400 text-teal-400 hover:bg-teal-400 hover:text-black px-8 py-3 rounded-full hover-lift"
          (onClick)="handleScheduleCall()">
          <svg class="mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
          </svg>
          Schedule a Call
        </app-button>
      </div>
      <div class="text-sm text-gray-400 space-y-1">
        <p>💬 WhatsApp: +91 90254 86901</p>
        <p>Quick response • Personalized consultation • Free initial discussion</p>
      </div>
    </div>
  </div>
</section>
