// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

interface FooterLink {
  name: string;
  path: string;
}

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {
  quickLinks: FooterLink[] = [
    { name: 'About Us', path: '/about' },
    { name: 'Our Offerings', path: '/offerings' },
    { name: 'Createch Internship', path: '/internship' },
    { name: 'Community', path: '/community' },
  ];

  services: string[] = [
    'Resin Art Creations',
    'Tech-Infused Artistry',
    'MIY Kits',
    'B2B Collaborations',
    'Bulk Orders',
  ];
}
<footer class="bg-gradient-to-t from-black to-gray-900 border-t border-gray-800">
  <div class="container mx-auto px-4 py-12">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
      <!-- Brand Section -->
      <div class="space-y-4">
        <div class="flex items-center space-x-3">
          <img src="/sa.jpg" alt="SA Logo" class="h-10 w-auto rounded-full">
          <div>
            <span class="text-lg font-playfair font-bold gradient-text">Stasis Artis</span>
            <p class="text-xs text-gray-400">Createch Studio</p>
          </div>
        </div>
        <p class="text-gray-300 text-sm leading-relaxed">
          India's First Women-Led MSME-Registered Createch Studio, fusing resin art with embedded technology.
        </p>
      </div>

      <!-- Quick Links -->
      <div class="space-y-4">
        <span class="text-lg font-semibold text-white">Quick Links</span>
        <div class="space-y-2">
          <a 
            *ngFor="let link of quickLinks"
            [routerLink]="link.path"
            class="block text-gray-300 hover:text-teal-400 transition-colors text-sm">
            {{ link.name }}
          </a>
        </div>
      </div>

      <!-- Services -->
      <div class="space-y-4">
        <span class="text-lg font-semibold text-white">Services</span>
        <div class="space-y-2">
          <p 
            *ngFor="let service of services"
            class="text-gray-300 text-sm">
            {{ service }}
          </p>
        </div>
      </div>

      <!-- Contact Info -->
      <div class="space-y-4">
        <span class="text-lg font-semibold text-white">Contact</span>
        <div class="space-y-3">
          <div class="flex items-center space-x-3 text-gray-300">
            <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            <span class="text-sm">Coimbatore, Tamil Nadu</span>
          </div>
          <div class="flex items-center space-x-3 text-gray-300">
            <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            <span class="text-sm">hello@stasisartis.com</span>
          </div>
          <div class="flex items-center space-x-3 text-gray-300">
            <svg class="h-4 w-4 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
            </svg>
            <span class="text-sm">+91 XXXXX XXXXX</span>
          </div>
        </div>

        <!-- Social Links -->
        <div class="flex space-x-4 pt-2">
          <a 
            href="#"
            class="w-8 h-8 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center text-black hover:shadow-lg transition-shadow">
            <svg class="h-4 w-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.174-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.097.118.112.221.083.343-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.746-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24.009 12.017 24.009c6.624 0 11.99-5.367 11.99-11.988C24.007 5.367 18.641.001.012.001z"/>
            </svg>
          </a>
          <a 
            href="#"
            class="w-8 h-8 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center text-black hover:shadow-lg transition-shadow">
            <svg class="h-4 w-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
            </svg>
          </a>
        </div>
      </div>
    </div>

    <!-- Bottom Section -->
    <div class="border-t border-gray-800 mt-8 pt-8">
      <div class="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
        <p class="text-center text-gray-400 text-sm font-playfair italic">
          "Art is eternal. Tech makes it boundless."
        </p>
        <p class="text-gray-400 text-sm">
          © 2024 Stasis Artis. All rights reserved.
        </p>
      </div>
    </div>
  </div>
</footer>

// src/components/Footer.jsx

import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Instagram, Linkedin, Mail, Phone, MapPin } from 'lucide-react';

const Footer = () => {
  return (
    <footer className="bg-gradient-to-t from-black to-gray-900 border-t border-gray-800">
      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {/* Brand Section */}
          <div className="space-y-4">
            <div className="flex items-center space-x-3">
              {/* <div className="w-10 h-10 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center font-bold text-black">
                SA
              </div> */}
                          <img src="/sa.jpg" alt="SA Logo" className="h-10 w-auto rounded-full" />

              <div>
                <span className="text-lg font-playfair font-bold gradient-text">Stasis Artis</span>
                <p className="text-xs text-gray-400">Createch Studio</p>
              </div>
            </div>
            <p className="text-gray-300 text-sm leading-relaxed">
              India's First Women-Led MSME-Registered Createch Studio, fusing resin art with embedded technology.
            </p>
            {/* <div className="text-xs text-gray-400">
              <p>MSME Registration: UDYAM-TN-02-00069559HH</p>
              <p>Micro Enterprise – Manufacturing & Services</p>
            </div> */}
          </div>

          {/* Quick Links */}
          <div className="space-y-4">
            <span className="text-lg font-semibold text-white">Quick Links</span>
            <div className="space-y-2">
              {[
                { name: 'About Us', path: '/about' },
                { name: 'Our Offerings', path: '/offerings' },
                { name: 'Createch Internship', path: '/internship' },
                { name: 'Community', path: '/community' },
              ].map((link) => (
                <Link
                  key={link.path}
                  to={link.path}
                  className="block text-gray-300 hover:text-teal-400 transition-colors text-sm"
                >
                  {link.name}
                </Link>
              ))}
            </div>
          </div>

          {/* Services */}
          <div className="space-y-4">
            <span className="text-lg font-semibold text-white">Services</span>
            <div className="space-y-2">
              {[
                'Resin Art Creations',
                'Tech-Infused Artistry',
                'MIY Kits',
                'B2B Collaborations',
                'Bulk Orders',
              ].map((service) => (
                <p key={service} className="text-gray-300 text-sm">
                  {service}
                </p>
              ))}
            </div>
          </div>

          {/* Contact Info */}
          <div className="space-y-4">
            <span className="text-lg font-semibold text-white">Contact</span>
            <div className="space-y-3">
              <div className="flex items-center space-x-3 text-gray-300">
                <MapPin className="h-4 w-4 text-teal-400" />
                <span className="text-sm">Coimbatore, Tamil Nadu</span>
              </div>
              <div className="flex items-center space-x-3 text-gray-300">
                <Mail className="h-4 w-4 text-teal-400" />
                <span className="text-sm">hello@stasisartis.com</span>
              </div>
              <div className="flex items-center space-x-3 text-gray-300">
                <Phone className="h-4 w-4 text-teal-400" />
                <span className="text-sm">+91 XXXXX XXXXX</span>
              </div>
            </div>

            {/* Social Links */}
            <div className="flex space-x-4 pt-2">
              <motion.a
                href="#"
                whileHover={{ scale: 1.1 }}
                className="w-8 h-8 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center text-black hover:shadow-lg transition-shadow"
              >
                <Instagram className="h-4 w-4" />
              </motion.a>
              <motion.a
                href="#"
                whileHover={{ scale: 1.1 }}
                className="w-8 h-8 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center text-black hover:shadow-lg transition-shadow"
              >
                <Linkedin className="h-4 w-4" />
              </motion.a>
            </div>
          </div>
        </div>

        {/* Bottom Section */}
        <div className="border-t border-gray-800 mt-8 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center text-gray-400 text-sm font-playfair italic"
            >
              "Art is eternal. Tech makes it boundless."
            </motion.p>
            <p className="text-gray-400 text-sm">
              © 2024 Stasis Artis. All rights reserved.
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
