// src/app/components/header/header.component.ts
import { Component, OnInit, HostListener } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

interface NavItem {
  name: string;
  path: string;
}

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  isOpen = false;
  scrolled = false;
  currentPath = '';

  navItems: NavItem[] = [
    { name: 'Home', path: '/' },
    { name: 'About Us', path: '/about' },
    { name: 'Our Offerings', path: '/offerings' },
    { name: 'Createch Internship', path: '/internship' },
    { name: 'Collaborations', path: '/collaborations' },
    { name: 'Community', path: '/community' },
    { name: 'Bulk Orders', path: '/bulk-orders' },
    { name: 'Contact', path: '/contact' },
  ];

  constructor(private router: Router) {}

  ngOnInit() {
    this.router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe((event: NavigationEnd) => {
        this.currentPath = event.url;
      });
  }

  @HostListener('window:scroll', ['$event'])
  onWindowScroll() {
    this.scrolled = window.pageYOffset > 50;
  }

  toggleMenu() {
    this.isOpen = !this.isOpen;
  }

  closeMenu() {
    this.isOpen = false;
  }

  isActive(path: string): boolean {
    return this.currentPath === path;
  }
}
<header 
  class="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
  [class.glass-effect]="scrolled"
  [class.shadow-sm]="scrolled"
  [class.bg-transparent]="!scrolled">
  
  <nav class="container mx-auto px-4 py-4">
    <div class="flex items-center justify-between">
      <a routerLink="/" class="flex items-center space-x-3">
        <img src="/sa.jpg" alt="SA Logo" class="h-10 w-auto rounded-full">
        <div>
          <h1 class="text-xl font-playfair font-bold text-white">Stasis Artis</h1>
          <p class="text-xs font-bold text-gray-400">Code n Craft</p>
        </div>
      </a>

      <!-- Desktop Navigation -->
      <div class="hidden lg:flex items-center space-x-8">
        <a 
          *ngFor="let item of navItems"
          [routerLink]="item.path"
          class="text-sm font-medium transition-colors hover:text-teal-400"
          [class.text-teal-400]="isActive(item.path)"
          [class.text-white]="!isActive(item.path)">
          {{ item.name }}
        </a>
      </div>

      <!-- Mobile Menu Button -->
      <button
        class="lg:hidden p-2 rounded-md hover:bg-gray-800 transition-colors"
        (click)="toggleMenu()">
        <svg 
          *ngIf="!isOpen"
          class="h-6 w-6 text-white" 
          fill="none" 
          viewBox="0 0 24 24" 
          stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
        <svg 
          *ngIf="isOpen"
          class="h-6 w-6 text-white" 
          fill="none" 
          viewBox="0 0 24 24" 
          stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Mobile Navigation -->
    <div 
      *ngIf="isOpen"
      class="lg:hidden mt-4 glass-effect rounded-lg p-4 animate-in slide-in-from-top duration-200">
      <a 
        *ngFor="let item of navItems"
        [routerLink]="item.path"
        class="block py-2 text-sm font-medium transition-colors hover:text-teal-400"
        [class.text-teal-400]="isActive(item.path)"
        [class.text-white]="!isActive(item.path)"
        (click)="closeMenu()">
        {{ item.name }}
      </a>
    </div>
  </nav>
</header>

// src/components/Header.jsx

import React, { useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';

const Header = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const location = useLocation();

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 50);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const navItems = [
    { name: 'Home', path: '/' },
    { name: 'About Us', path: '/about' },
    { name: 'Our Offerings', path: '/offerings' },
    { name: 'Createch Internship', path: '/internship' },
    { name: 'Collaborations', path: '/collaborations' },
    { name: 'Community', path: '/community' },
    { name: 'Bulk Orders', path: '/bulk-orders' },
    { name: 'Contact', path: '/contact' },
  ];

  return (
    <motion.header
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        scrolled ? 'glass-effect shadow-sm' : 'bg-transparent'
      }`}
    >
      <nav className="container mx-auto px-4 py-4">
        <div className="flex items-center justify-between">
          <Link to="/" className="flex items-center space-x-3">
            {/* <div className="w-12 h-12 rounded-full bg-gradient-to-r from-teal-400 to-cyan-400 flex items-center justify-center font-bold text-black text-xl">
              SA
            </div> */}
            <img src="/sa.jpg" alt="SA Logo" className="h-10 w-auto rounded-full" />
            <div>
              {/* <h1 className="text-xl font-playfair font-bold gradient-text ">Stasis Artis</h1> */}
              <h1 className="text-xl font-playfair font-bold  ">Stasis Artis</h1>
              <p className="text-xs font-bold text-gray-400">Code n Craft</p>
            </div>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden lg:flex items-center space-x-8">
            {navItems.map((item) => (
              <Link
                key={item.path}
                to={item.path}
                className={`text-sm font-medium transition-colors hover:text-teal-400 ${
                  location.pathname === item.path ? 'text-teal-400' : 'text-white'
                }`}
              >
                {item.name}
              </Link>
            ))}
          </div>

          {/* Mobile Menu Button */}
          <Button
            variant="ghost"
            size="icon"
            className="lg:hidden"
            onClick={() => setIsOpen(!isOpen)}
          >
            {isOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
          </Button>
        </div>

        {/* Mobile Navigation */}
        <AnimatePresence>
          {isOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="lg:hidden mt-4 glass-effect rounded-lg p-4"
            >
              {navItems.map((item) => (
                <Link
                  key={item.path}
                  to={item.path}
                  className={`block py-2 text-sm font-medium transition-colors hover:text-teal-400 ${
                    location.pathname === item.path ? 'text-teal-400' : 'text-white'
                  }`}
                  onClick={() => setIsOpen(false)}
                >
                  {item.name}
                </Link>
              ))}
            </motion.div>
          )}
        </AnimatePresence>
      </nav>
    </motion.header>
  );
};

export default Header;
